#!/usr/bin/env python3
"""Assemble T5-compatible A7Z images on Linux, using file-backed loop devices.

Dependencies: python3, util-linux (including sfdisk), dosfstools, e2fsprogs,
rsync, and the pinned T5 U-Boot package in the prepared rootfs. Run as root.
Only a newly-created regular image file is accepted; existing outputs and
physical block-device paths are never build targets.
"""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import uuid

MIB = 1024 * 1024
LINUX_TYPE = "0FC63DAF-8483-4772-8E79-3D69D8477DE4"
EFI_TYPE = "C12A7328-F81F-11D2-BA4B-00A0C93EC93B"
# Exact sector geometry from the rsdk-t5 build-512-image/build-4096-image assets.
GEOMETRY = {512: (32768, 65536, 679936), 4096: (32768, 65536, 142336)}


def run(*args, input=None, capture=False, ok=(0,)):
    result = subprocess.run([str(a) for a in args], input=input, text=True,
                            stdout=subprocess.PIPE if capture else None,
                            check=False)
    if result.returncode not in ok:
        raise RuntimeError(f"Command failed ({result.returncode}): {' '.join(map(str, args))}")
    return result.stdout.strip() if capture else result.returncode


def geometry(sector_size, root_size_mib):
    if sector_size not in GEOMETRY or root_size_mib < 256:
        raise ValueError("sector size must be 512/4096; root size must be at least 256 MiB")
    config, efi, root = GEOMETRY[sector_size]
    # The official -34 end sector leaves 33 trailing logical sectors in either image.
    sectors = root_size_mib * MIB // sector_size
    return {"sector_size": sector_size, "disk_bytes": (root + sectors + 33) * sector_size,
            "partitions": [{"number": 1, "name": "config", "start": config,
                            "size": efi - config, "type": LINUX_TYPE, "attributes": 0},
                           {"number": 2, "name": "efi", "start": efi,
                            "size": root - efi, "type": EFI_TYPE, "attributes": 4},
                           {"number": 3, "name": "rootfs", "start": root,
                            "size": sectors, "type": LINUX_TYPE, "attributes": 4}]}


def root_arguments(text, root_uuid):
    words = [word for word in text.split() if not word.startswith("root=")]
    if not any(word == "rootwait" or word.startswith("rootwait=") for word in words):
        words.append("rootwait")
    return " ".join([f"root=UUID={root_uuid}", *words])


def rewrite_extlinux(text, root_uuid):
    count = 0
    result = []
    for line in text.splitlines():
        match = re.match(r"^(\s*append\s+)(.*)$", line, re.I)
        if match:
            count += 1
            result.append(match.group(1) + root_arguments(match.group(2), root_uuid))
        else:
            result.append(line)
    if not count:
        raise ValueError("extlinux.conf contains no APPEND line; prepare the T5 extlinux configuration first")
    return "\n".join(result) + "\n"


def rewrite_fstab(text, uuids):
    result = []
    for line in text.splitlines():
        fields = line.split()
        if fields and not line.lstrip().startswith("#") and len(fields) > 1:
            if fields[1] in ("/", "/config", "/boot/efi"):
                continue
        result.append(line)
    result.extend(["# A7Z image-specific filesystems; generated by tools/image.py",
                   f"UUID={uuids['rootfs']} / ext4 defaults 0 1",
                   f"UUID={uuids['config']} /config vfat defaults,x-systemd.automount,fmask=0077,dmask=0077 0 2",
                   f"UUID={uuids['efi']} /boot/efi vfat defaults,x-systemd.automount,fmask=0077,dmask=0077 0 2"])
    return "\n".join(result) + "\n"


def beneath(root, relative):
    path = root / relative
    if not path.resolve().is_relative_to(root.resolve()):
        raise ValueError(f"Path escapes prepared rootfs: {path}")
    return path


def update_boot_files(root, uuids, manifest):
    extlinux = beneath(root, "boot/extlinux/extlinux.conf")
    cmdline = beneath(root, "etc/kernel/cmdline")
    fstab = beneath(root, "etc/fstab")
    extlinux.write_text(rewrite_extlinux(extlinux.read_text(), uuids["rootfs"]))
    lines = [line.strip() for line in cmdline.read_text().splitlines()
             if line.strip() and not line.lstrip().startswith("#")]
    if len(lines) != 1:
        raise ValueError("/etc/kernel/cmdline must contain one non-comment command line")
    cmdline.write_text(root_arguments(lines[0], uuids["rootfs"]) + "\n")
    fstab.write_text(rewrite_fstab(fstab.read_text() if fstab.exists() else "", uuids))
    for path in ("etc/a7z-image.json", "config/a7z-image.json"):
        beneath(root, path).write_text(json.dumps(manifest, indent=2) + "\n")


def require_commands():
    commands = ("losetup", "sfdisk", "mount", "umount", "mkfs.fat", "mkfs.ext4",
                "e2fsck", "blkid", "blockdev", "rsync", "bash", "findmnt")
    missing = [command for command in commands if not shutil.which(command)]
    if missing:
        raise RuntimeError("Missing build dependencies: " + ", ".join(missing))


def assert_loop(loop, image, sector_size):
    if not re.fullmatch(r"/dev/loop[0-9]+", loop):
        raise RuntimeError(f"Unexpected loop-device name: {loop}")
    records = json.loads(run("losetup", "--json", "--output", "NAME,BACK-FILE,LOG-SEC", loop, capture=True))
    device = records["loopdevices"][0]
    if Path(device["back-file"]).resolve() != image.resolve() or int(device["log-sec"]) != sector_size:
        raise RuntimeError("Loop backing file or logical sector size does not match this build")


def reject_rootfs_mounts(rootfs):
    records = json.loads(run("findmnt", "--json", "--list", "--output", "TARGET", capture=True))
    for entry in records.get("filesystems", []):
        target = Path(entry["target"]).resolve()
        if target != rootfs and target.is_relative_to(rootfs):
            raise ValueError(f"Unmount nested build mount before imaging: {target}")


def build(args):
    if sys.platform != "linux" or os.geteuid() != 0:
        raise RuntimeError("Build requires Linux root privileges (sudo); use a Linux filesystem for rootfs")
    require_commands()
    rootfs = Path(args.rootfs).resolve(strict=True)
    if not rootfs.is_dir() or rootfs == Path("/"):
        raise ValueError("--rootfs must be a prepared rootfs directory, not /")
    reject_rootfs_mounts(rootfs)
    config_dir = Path(args.config_dir).resolve(strict=True) if args.config_dir else None
    if config_dir is not None and not config_dir.is_dir():
        raise ValueError("--config-dir must be a directory")
    output_arg = Path(args.output).absolute()
    if output_arg.is_symlink() or output_arg.exists():
        raise ValueError("Refusing existing output (including block devices and symlinks)")
    output = output_arg.parent.resolve(strict=True) / output_arg.name
    if output.is_relative_to(rootfs):
        raise ValueError("Output must be outside the source rootfs")
    for suffix in (".json", ".sha256"):
        if Path(str(output) + suffix).exists():
            raise ValueError(f"Refusing existing sidecar: {output}{suffix}")
    for relative in ("boot/extlinux/extlinux.conf", "etc/kernel/cmdline"):
        if not beneath(rootfs, relative).is_file():
            raise ValueError(f"Missing prepared boot configuration: {relative}")
    # --bootloader-dir is the board directory containing setup.sh and the binary.
    bootdir = Path(args.bootloader_dir).resolve(strict=True) if args.bootloader_dir else (
        rootfs / "usr/lib/u-boot/radxa-a733").resolve(strict=True)
    setup = bootdir / "setup.sh"
    binary = bootdir / "u-boot-sunxi-with-spl.bin"
    if not setup.is_file() or not binary.is_file():
        raise ValueError("T5 bootloader directory must contain setup.sh and u-boot-sunxi-with-spl.bin")
    # Reject older alternative blobs: upstream setup prefers them if present.
    if any((bootdir / name).exists() for name in ("boot0_sdcard.bin", "boot0_ufs.bin", "boot_package.fex")):
        raise ValueError("Legacy boot0/boot_package blobs are present; use the clean pinned T5 bootloader package")
    root_size = args.root_size_mib
    if root_size is None:
        # Apparent size leaves room for sparse files becoming allocated in the filesystem.
        used = int(run("du", "-sm", "--apparent-size", rootfs, capture=True).split()[0])
        root_size = max(2048, ((int(used * 1.25) + 1023) // 256) * 256)
    layout = geometry(args.sector_size, root_size)
    offset = 2064 * 512 if args.sector_size == 4096 else 256 * 512
    if offset + binary.stat().st_size > layout["partitions"][0]["start"] * args.sector_size:
        raise ValueError("Bootloader binary overlaps the config partition")
    manifest = {"format": "a7z-archlinuxarm-image-v1", "baseline": "rsdk-t5",
                **layout, "root_size_mib": root_size,
                "private_seed_included": config_dir is not None,
                "bootloader_sha256": hashlib.sha256(binary.read_bytes()).hexdigest(),
                "setup_sha256": hashlib.sha256(setup.read_bytes()).hexdigest(),
                "bootloader_offset": offset, "disk_guid": str(uuid.uuid4())}
    uuids = {"rootfs": str(uuid.uuid4()), "config": uuid.uuid4().hex[:8].upper(),
             "efi": uuid.uuid4().hex[:8].upper()}
    for name in ("config", "efi"):
        uuids[name] = uuids[name][:4] + "-" + uuids[name][4:]
    manifest["filesystem_uuids"] = uuids
    for partition in manifest["partitions"]:
        partition["uuid"] = str(uuid.uuid4())
    with tempfile.TemporaryDirectory(prefix=".a7z-image-", dir=output.parent) as temporary:
        temp = Path(temporary)
        image = temp / "image.partial"
        with image.open("xb") as handle:
            handle.truncate(layout["disk_bytes"])
        loop = None
        mounts = []
        try:
            loop = run("losetup", "--find", "--show", "--sector-size", args.sector_size,
                       "--partscan", image, capture=True)
            assert_loop(loop, image, args.sector_size)
            table = f"label: gpt\nlabel-id: {manifest['disk_guid']}\nunit: sectors\n"
            for part in manifest["partitions"]:
                table += (f"start={part['start']}, size={part['size']}, type={part['type']}, "
                          f"uuid={part['uuid']}, name=\"{part['name']}\"" +
                          (", attrs=LegacyBIOSBootable" if part["attributes"] else "") + "\n")
            run("sfdisk", loop, input=table)
            if shutil.which("udevadm"):
                run("udevadm", "settle")
            for number in (1, 2, 3):
                if not Path(f"{loop}p{number}").is_block_device():
                    raise RuntimeError(f"Loop partition not available: {loop}p{number}; verify kernel loop partition support")
            for number, name in ((1, "config"), (2, "efi")):
                run("mkfs.fat", "-S", args.sector_size, "-i", uuids[name].replace("-", ""),
                    "-n", name, f"{loop}p{number}")
            # Disable the newer orphan_file feature (not understood by the T5 U-Boot reader).
            run("mkfs.ext4", "-F", "-b", "4096", "-O", "^orphan_file,^metadata_csum_seed",
                "-E", "lazy_itable_init=0,lazy_journal_init=0", "-m", "0", "-L", "rootfs",
                "-U", uuids["rootfs"], f"{loop}p3")
            root = temp / "root"
            root.mkdir()
            run("mount", f"{loop}p3", root)
            mounts.append(root)
            for relative, number in (("config", 1), ("boot/efi", 2)):
                mount = root / relative
                mount.mkdir(parents=True)
                run("mount", f"{loop}p{number}", mount)
                mounts.append(mount)
            # FAT cannot preserve ownership/xattrs. Copy its payload separately.
            run("rsync", "-aHAX", "--numeric-ids", "--exclude=/config/***", "--exclude=/boot/efi/***",
                str(rootfs) + "/", str(root) + "/")
            for relative in ("config", "boot/efi"):
                source = beneath(rootfs, relative)
                if source.is_dir():
                    run("rsync", "-rt", "--modify-window=1", str(source) + "/", str(root / relative) + "/")
            if config_dir is not None:
                run("rsync", "-rt", "--modify-window=1", str(config_dir) + "/", str(root / "config") + "/")
            update_boot_files(root, uuids, manifest)
            for mount in reversed(mounts):
                run("umount", mount)
            mounts.clear()
            run("e2fsck", "-f", "-n", f"{loop}p3")
            for number, name in ((1, "config"), (2, "efi"), (3, "rootfs")):
                observed = run("blkid", "-s", "UUID", "-o", "value", f"{loop}p{number}", capture=True)
                if observed.lower() != uuids[name].lower():
                    raise RuntimeError(f"Unexpected {name} filesystem UUID: {observed}")
            assert_loop(loop, image, args.sector_size)
            run("sfdisk", "--verify", loop)
            run("losetup", "--detach", loop)
            loop = None
            # Execute the official host-side script against the regular image, with explicit sector size.
            run("bash", setup, "update_bootloader", image, args.sector_size)
            with image.open("rb") as handle:
                handle.seek(offset)
                if handle.read(binary.stat().st_size) != binary.read_bytes():
                    raise RuntimeError("Bootloader bytes at the T5 offset do not match the pinned binary")
            digest = hashlib.sha256()
            with image.open("rb") as handle:
                for chunk in iter(lambda: handle.read(8 * MIB), b""):
                    digest.update(chunk)
            manifest["sha256"] = digest.hexdigest()
            # Publish atomically without replacing an output created during the build.
            os.link(image, output)
            with Path(str(output) + ".json").open("x") as handle:
                json.dump(manifest, handle, indent=2)
                handle.write("\n")
            with Path(str(output) + ".sha256").open("x") as handle:
                handle.write(f"{manifest['sha256']}  {output.name}\n")
            print(json.dumps({"output": str(output), **manifest}, indent=2))
        finally:
            cleanup_error = None
            for mount in reversed(mounts):
                try:
                    run("umount", mount)
                except RuntimeError as exc:
                    cleanup_error = exc
            if loop and not cleanup_error:
                assert_loop(loop, image, args.sector_size)
                run("losetup", "--detach", loop)
            if cleanup_error:
                # Never recursively remove a directory while a filesystem is still mounted there.
                temporary_path = temp.with_name(temp.name + "-NEEDS-UNMOUNT")
                temp.rename(temporary_path)
                raise RuntimeError(f"Cleanup failed; unmount manually before removing {temporary_path}") from cleanup_error


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    build_parser = commands.add_parser("build", help="assemble one new SD/UFS regular image file")
    build_parser.add_argument("--rootfs", required=True)
    build_parser.add_argument("--output", required=True)
    build_parser.add_argument("--sector-size", required=True, type=int, choices=(512, 4096))
    build_parser.add_argument("--root-size-mib", type=int)
    build_parser.add_argument("--bootloader-dir", help="board directory containing pinned T5 setup.sh and binary")
    build_parser.add_argument("--config-dir", help="optional first-boot seed files copied to the config FAT filesystem")
    args = parser.parse_args()
    try:
        build(args)
    except (OSError, RuntimeError, ValueError) as exc:
        parser.exit(1, f"image build refused/failed: {exc}\n")


if __name__ == "__main__":
    main()
